### ISSUE TITLE
Depth estimation in evaluate

### ISSUE THREAD

**Issue by tsian077** [priya-dwivedi/Deep-Learning#110]
hi~ i want to know why the different in the utils.py evaluate function with origin Densedepth code
your code in line  131 in utils.py:
`      
# Compute errors per image in batch
       for j in range(len(true_y)):
            
            errors = compute_errors(true_y[j], (0.5 * pred_y[j]) + (0.5 * np.fliplr(pred_y_flip[j])))
            
            for k in range(len(errors)):
                depth_scores[k][(i*bs)+j] = errors[k]

    e = depth_scores.mean(axis=1)
#==============      
`

origin Densedepth code line 131 in utils.py:
`        
# Compute errors per image in batch
        for j in range(len(true_y)):
            predictions.append(   (0.5 * pred_y[j]) + (0.5 * np.fliplr(pred_y_flip[j]))   )
            testSetDepths.append(   true_y[j]   )

    predictions = np.stack(predictions, axis=0)
    testSetDepths = np.stack(testSetDepths, axis=0)

    e = compute_errors(predictions, testSetDepths)
`

The part of code make the rmse value change very much
Thanks

**Comment by priya-dwivedi** [comment]
I made changes to the utils to have different types of visualizations.
