### ISSUE TITLE
mask rcnn damage detection - Are the damages mapped in - 'via region data.json'? file  

### ISSUE THREAD

**Issue by bharathcs24** [priya-dwivedi/Deep-Learning#113]
Hi,

mask rcnn damage detection - Are the damages mapped in - 'via region data.json'?

**Comment by priya-dwivedi** [comment]
Yes the via_region_data.json should have annotations for the area of damage

**Comment by sumit1212** [comment]
But how to create JSON file through program or manually. Because I have test model with own dataset but it give me error.

How to create json file.
