### ISSUE TITLE
Advice/guidance required for english writer identification 

### ISSUE THREAD

**Issue by researchase** [priya-dwivedi/Deep-Learning#127]
We tried the jupyter notebook and got good accuracy, thank you so much for sharing your work.
Our objective is to identify if a given handwritting is a same person or not,  so if we give snippet of sentence images from 2 documents written by same person the output of the model should be 1 if not 0

do you any suggestions on how we can do this?

Thanks 
Ashwin

**Comment by priya-dwivedi** [comment]
You have to get embeddings from a layer deeper in the network and then you can compare embeddings b/w different writers to measure similarity.
