### ISSUE TITLE
after run the file, no output.

### ISSUE THREAD

**Issue by km5ar** [priya-dwivedi/Deep-Learning#128]
after run `python question_answering_inference.py - ques 'How many confirmed cases are in Mexico?' - source 'sample2.txt'` on the file below, nothing happend. Then i tried to run the py file inside of the spyder, it shows error below. how can i solve the problem

<img width="874" alt="terminal" src="https://user-images.githubusercontent.com/54015474/98196629-9d9a8300-1ef2-11eb-90fe-9a14b2d4d46b.png">

<img width="676" alt="sample2" src="https://user-images.githubusercontent.com/54015474/98196676-c02c9c00-1ef2-11eb-93c7-4521a27bb8bc.png">

<img width="621" alt="error" src="https://user-images.githubusercontent.com/54015474/98196858-3d581100-1ef3-11eb-80e2-f17090621ad0.png">

**Comment by priya-dwivedi** [comment]
The error suggests that your source is None. Please pass string directly and check again.
