### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by ngksai93** [priya-dwivedi/Deep-Learning#15]
python /home/gopalakrishna/tfrecords/create_tf.py 
/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/gopalakrishna/work/models/object_detection/utils/dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
Traceback (most recent call last):
  File "/home/gopalakrishna/tfrecords/create_tf.py", line 213, in <module>
    tf.app.run()
  File "/home/gopalakrishna/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/gopalakrishna/tfrecords/create_tf.py", line 208, in main
    image_dir, train_examples)
  File "/home/gopalakrishna/tfrecords/create_tf.py", line 177, in create_tf_record
    tf_example = dict_to_tf_example(data, label_map_dict, image_dir)
  File "/home/gopalakrishna/tfrecords/create_tf.py", line 120, in dict_to_tf_example
    class_name = get_class_name_from_filename(data['filename'])
  File "/home/gopalakrishna/tfrecords/create_tf.py", line 61, in get_class_name_from_filename
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by crackets14** [comment]
It seems like the author of this code simply copied the scripts of tensorflow and did not adapt anything, which is, indeed, a bit annoying.

The names of the files are "toyXYZ.jpg" and not "toy_XYZ.jpg". Thats why re.match cannot find anything.
```
def get_class_name_from_filename(file_name):
  match = re.match(r'([A-Za-z_]+)(_[0-9]+\.jpg)', file_name, re.I)
  return match.groups()[0]

```

change to 

```
def get_class_name_from_filename(file_name):
  match = re.match(r'([A-Za-z_]+)([0-9]+\.jpg)', file_name, re.I)
  return match.groups()[0]

```

**Comment by ngksai93** [comment]
thank you
