### ISSUE TITLE
How do I train on my custom dataset?

### ISSUE THREAD

**Issue by Zumbalamambo** [priya-dwivedi/Deep-Learning#22]
Can you please add some additional information about how to train mask rcnn? everything throws error

**Comment by Zumbalamambo** [comment]
```
WARNING:root:Could not find annotations/xmls/toy8.xml, ignoring example.
WARNING:root:Could not find annotations/xmls/toy22.xml, ignoring example.
WARNING:root:Could not find annotations/xmls/toy13.xml, ignoring example.
WARNING:root:Could not find annotations/xmls/toy32.xml, ignoring example.
WARNING:root:Could not find annotations/xmls/toy30.xml, ignoring example.
WARNING:root:Could not find annotations/xmls/toy15.xml, ignoring example.
WARNING:root:Could not find annotations/xmls/toy7.xml, ignoring example.
```

**Comment by vijaydwivedi75** [comment]
I am looking for the same solution. This .ipynb notebook in Custom Mask RCNN has no code for training.

How do I train on my own custom data set?
@priya-dwivedi @Zumbalamambo ??

**Comment by Zumbalamambo** [comment]
this repo is full of bugs. you cant use this code smoothly to train as there are a lot of missing pieces of dots. I once have managed to train it but i would suggest you to  Use [this](https://github.com/matterport/Mask_RCNN)
