### ISSUE TITLE
[Custom_Mask_RCNN] Labeling masks correctly

### ISSUE THREAD

**Issue by mldm4** [priya-dwivedi/Deep-Learning#24]
Thanks for your great work.

I am trying to label my images as you suggest with PixelAnnotationTool and I wonder what ID to use for the object I want to segment.

According to lines 121 and 122 in `create_pet_tf_record.py`:
```
nonbackground_indices_x = np.any(mask_np != 2, axis=0)
nonbackground_indices_y = np.any(mask_np != 2, axis=1)
```
I understand background instance must have pixel value 2 and any other pixel value will represent a different label, i.e.: 0 for car, 1 for toy, 3 for apple, etc.

I would like to know if my assumption is correct and whether this has been the way you have proceeded.

Thanks again.

**Comment by priya-dwivedi** [comment]
Yes this is a good approach
