### ISSUE TITLE
Saving trained weights

### ISSUE THREAD

**Issue by ashwinijoshigithub** [priya-dwivedi/Deep-Learning#29]
After training the model, code does not have any block to save the trained weights. Do I need to add my own block for that or I am missing out on anything? If yes, could you guide me on where to add those lines? @priya-dwivedi

**Comment by 008karan** [comment]
I am facing a similar problem. After training is completed its not giving me anything. Its just stops. No weight file. Any suggestion.

**Comment by nikhilkhandelwal0702** [comment]
@ashwinijoshigithub and @priya-dwivedi can you help us how did you solved this problem.
i am running the code on clouderizer with colab

**Comment by ashwinijoshigithub** [comment]
@008karan you can just add line model.save_weights(your filepath) after model.train line. Please check syntax for it once. It will save the weights in a .h5 file.

**Comment by priya-dwivedi** [comment]
Thanks. The suggestion above should work.
