### ISSUE TITLE
can't find trained weights file?

### ISSUE THREAD

**Issue by 008karan** [priya-dwivedi/Deep-Learning#30]
I was able to train car damage detection example. But after training, I could not locate the weight file(.h5). When I run inspect_custom_model.ipynb it gives the error that could not find mask_rcnn_damage.h5 file.

**Comment by priya-dwivedi** [comment]
please check your root folder or on linux your documents folder

**Comment by 008karan** [comment]
I checked but could not find it. There nothing mentioned in custom.py about where is trained weights are saved and in  inspect_custom_model notebook there is directly mentioned path of weight file= mask_rcnn_damage.h5.

**Comment by 008karan** [comment]
finally got!

**Comment by NexusHero** [comment]
Could you tell me where it was, @008karan ?

**Comment by NexusHero** [comment]
It's located in the _log-folder_ within the _root_ directory.
