### ISSUE TITLE
cannot find mask_rcnn_damage_0010.h5

### ISSUE THREAD

**Issue by umair-sabir** [priya-dwivedi/Deep-Learning#33]
Hi,

when i run the file inspect_custom_weight and inspect_custom_model. I get the following error.

OSError                                   Traceback (most recent call last)
<ipython-input-11-5659c5589710> in <module>()
      8 # Load weights
      9 print("Loading weights ", weights_path)
---> 10 model.load_weights(weights_path, by_name=True)

OSError: Unable to open file (unable to open file: name = 'mask_rcnn_damage_0010.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

It seems., it is not able to load the model.
Can you help me out with this.
Thanks

**Comment by nikhilkhandelwal0702** [comment]
@umair-sabir i am also getting same error can you tell how did you solve the error

**Comment by mayankmehtani** [comment]
@nikhilkhandelwal0702 look in the logs folder it is there in one of the the enclosing folders.
