### ISSUE TITLE
Mask-RCNN: Multiple false detections for 'toy' dataset

### ISSUE THREAD

**Issue by tghoshmo** [priya-dwivedi/Deep-Learning#50]
Hi,
When I train the model with the 'toy' data-set and evaluate the performance of the trained model on test images using mask_rcnn_custom_images.ipynb, I get the following results. 

![image](https://user-images.githubusercontent.com/31314634/50427390-a0df7500-086c-11e9-98fd-8dcebb3350ef.png)
![image](https://user-images.githubusercontent.com/31314634/50427394-b2c11800-086c-11e9-9875-6d1f0ae5267b.png)
![image](https://user-images.githubusercontent.com/31314634/50427395-b9e82600-086c-11e9-8f22-1229d9695a87.png)

Clearly, there are multiple false detections contrary to what is expected. I would appreciate if anyone could point out where I maybe going wrong and suggest possible way-outs.

Thanks.

**Comment by xenc0d3r** [comment]
This girl and her github work sucks.

**Comment by priya-dwivedi** [comment]
@xenc0d3r - Before you berate me, can you share details of what you tried? The above model is trained with very little data and doesn't generalize. What I hope to provide through my code and blogs is the ability for you to train on your own data
If you have any errors, please share details of what you tried and where it failed.
