### ISSUE TITLE
Custom mask rcnn, cannot parse label file.

### ISSUE THREAD

**Issue by antithing** [priya-dwivedi/Deep-Learning#56]
Hi, and thanks for making this code available. I am trying to run the mask rcnn demo. I have created 
'data/pet_label_map.pbtxt' 
which contains:

'item {
 id: 1
 name: ‘toy’
}'

but when i run 

`python create_pet_tf_record.py`

I get :

`label_map = load_labelmap(label_map_path)
  File "X:\dev\sandbox_bsharp\ML\models\research\object_detection\utils\label_map_util.py", line 138, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'`

What am i doing wrong here?

Thanks again.

**Comment by priya-dwivedi** [comment]
Name needs to be first and then ID. See thread below:
https://github.com/tensorflow/models/issues/4200
