### ISSUE TITLE
cannot find carl.h5

### ISSUE THREAD

**Issue by goalkeeperfyc** [priya-dwivedi/Deep-Learning#58]
When I try to run code

top_model_weights_path = 'car1.h5'
from PIL import Image
model = load_model(top_model_weights_path)

An error raised: OSError: Unable to open file (unable to open file: name = 'car1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I went through my mac and didn't find any file named carl.h5

Thank you for your help!

**Comment by goalkeeperfyc** [comment]
I am sorry for raising this question. The car1.h5 is a model initialized from executing code. No code running, no car1.h5

**Comment by Sujeetkumar006** [comment]
Hello Goalkeeperfyc,

Even I am facing the same issue. How did you fixed it. Thanks in advance!!

**Comment by goalkeeperfyc** [comment]
> Hello Goalkeeperfyc,
> 
> Even I am facing the same issue. How did you fixed it. Which should should be running?., Please help..
> 
> Thanks in advance!!

Hi Sujeetkumar,

car1.h5 is a model file created by python file CNN_model_for_occupany.ipynb. As long as you run that python file, you will get car1.h5 file.
