### ISSUE TITLE
NoneType object has no attribute groups

### ISSUE THREAD

**Issue by Janekxyz** [priya-dwivedi/Deep-Learning#6]
Hi!
I have a problem with creating record files with your create_pet_tf_record.py version.  When I call:
`python object_detection/dataset_tools/create_pet_tf_record.py --label_map_path=object_detection/data/label.pbtxt --data_dir=`pwd` --output_dir=`pwd``

it returns me this error:

 File "object_detection/dataset_tools/create_pet_tf_record.py", line 204, in <module>
    tf.app.run()
  File "/Users/user/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 199, in main
    image_dir, train_examples)
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 168, in create_tf_record
    tf_example = dict_to_tf_example(data, label_map_dict, image_dir)
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 112, in dict_to_tf_example
    class_name = get_class_name_from_filename(data['filename'])
  File "object_detection/dataset_tools/create_pet_tf_record.py", line 57, in get_class_name_from_filename
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

Can anyone know the solution of this problem?

**Comment by Janekxyz** [comment]
Solved problem. Reason was wrong picture names. Different than in map.pbtxt.

**Comment by Mr-Optimistic** [comment]
Hi..I'm facing the same issue...can you share me your working map.pbtxt..thanks

**Comment by EpitomeOfEnigma** [comment]
Same issue, please explain more about 'map.pbtxt'. thanks.

**Comment by bassmaamn** [comment]
Hello, what about 2 classes? how should the images be named?

**Comment by TheFlashover** [comment]
Faced same issue.
`File "object_detection/dataset_tools/create_pet_tf_record.py", line 69,`
`in get_class_name_from_filename
return match.groups()[0]`
`AttributeError: 'NoneType' object has no attribute 'groups'`

Because of these lines in file _**create_pet_tf_record.py**_:
`match = re.match(r'([A-Za-z_]+)(_[0-9]+\.jpg)', file_name, re.I)`
 `return match.groups()[0]`

Just changed filenames from *.jpeg -> *.jpg and it helped.

**Comment by sahatprasad** [comment]
how should the image name be changed if there are 2 classes?

**Comment by zazgf** [comment]
or maybe change 
`match = re.match(r'([A-Za-z_]+)(_[0-9]+\.jpg)', file_name, re.I)` to 
`match = re.match(r'([A-Za-z]+)([0-9]+\.jpg)', file_name, re.I)`
