### ISSUE TITLE
ValueError: Layer #389 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 8) dtype=float32_ref> has shape (1024, 8), but the saved weight has shape (1024, 324).

### ISSUE THREAD

**Issue by angyee** [priya-dwivedi/Deep-Learning#61]
while running below getting error

sudo python3 custom.py splash --weights=/home/mask_rcnn_coco.h5    --image=./customImages/train/image17.jpg 

@priya-dwivedi @priya-dwivedi

**Comment by nyknstyn** [comment]
Getting same error.

**Comment by priya-dwivedi** [comment]
You have to change number of classes. Please follow the thread below:
https://github.com/matterport/Mask_RCNN/issues/849
