### ISSUE TITLE
via_region_data.json file not found!

### ISSUE THREAD

**Issue by kumarankit1996** [priya-dwivedi/Deep-Learning#63]
I have been trying to replicate the car damage detection for understanding Mask RCNN training using blog:https://www.analyticsvidhya.com/blog/2018/07/building-mask-r-cnn-model-detecting-damage-cars-python/

I have copied the custom.py to balloon.py code of https://github.com/matterport/Mask_RCNN cloned balloon.py and also copied the customImages folder from this project into the cloned but I keep on getting the file not found error!
I used this command to train:
python3 balloon.py train --dataset=/Users/ankit/Desktop/Internship/proj/Mask_RCNN/customImages/train  --weights=coco

Please let me know if I am missing anything?

**Comment by priya-dwivedi** [comment]
use custom.py instead balloon.py. Its a modified version of balloon.py for custom model training.

**Comment by kumarankit1996** [comment]
Yeah, I am using the same custom.py code with balloon.py name!

**Comment by priya-dwivedi** [comment]
What is the error? If it is missing via_region_data.json then check if this file is in customImages/train. The json file here has the mask annotations. You can get it from the link below:
https://github.com/priya-dwivedi/Deep-Learning/tree/master/mask_rcnn_damage_detection/customImages/train
