### ISSUE TITLE
despth_estimation problem

### ISSUE THREAD

**Issue by Foexy** [priya-dwivedi/Deep-Learning#65]
OSError: Unable to open file (unable to open file: name = './models/1557483797-n10138-e20-bs5-lr0.0001-densedepth_nyu/weights.06-0.12.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by priya-dwivedi** [comment]
Please download model from https://s3-eu-west-1.amazonaws.com/densedepth/nyu.h5
