### ISSUE TITLE
How to set Values in create_pet_tf_record.py

### ISSUE THREAD

**Issue by Aniket1492** [priya-dwivedi/Deep-Learning#66]
I am following your Doc : https://www.kdnuggets.com/2018/02/building-toy-detector-tensorflow-object-detection-api.html

i am trying to set value in create_pet_tf_record.py, Where i am getting the issue as follows -

  File "C:\Aniket\TensorflowObjectDetection\Objectdetection\create_pet_tf_record.py", line 45, in <module>
    from object_detection.utils import label_map_util
  File "C:\Python35\lib\site-packages\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'

need your suggestion.
Thanks in Advance.

**Comment by priya-dwivedi** [comment]
Please follow instructions for installing tensorflow object detection at :+1: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
