### ISSUE TITLE
# Test video of "soccer_team_prediction/soccer_realtime.ipynb"

### ISSUE THREAD

**Issue by shliang0603** [priya-dwivedi/Deep-Learning#68]
@priya-dwivedi  Hi, can you send me the test video of  "soccer_team_prediction/soccer_realtime.ipynb".  The test video I found worked poorly. Thank  you.

**Comment by priya-dwivedi** [comment]
This is the video I used. You can cut out segments of it:
https://www.youtube.com/watch?v=fR-txBJG-B4
