### ISSUE TITLE
No such file or directory: '/path/to/datasetfolder/train/via_region_data.json'

### ISSUE THREAD

**Issue by Kulothungan8297** [priya-dwivedi/Deep-Learning#80]
Hi, I am following your analyticsvidya blog to run the code , but when I try to run the training command , i get the following error. Can you share if you know the solution?

https://www.analyticsvidhya.com/blog/2018/07/building-mask-r-cnn-model-detecting-damage-cars-python/

Traceback (most recent call last):
  File "custom.py", line 364, in <module>
    train(model)
  File "custom.py", line 184, in train
    dataset_train.load_custom(args.dataset, "train")
  File "custom.py", line 115, in load_custom
    annotations1 = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/datasetfolder/train/via_region_data.json'

The json file is loacted in the following path.

"/content/drive/My Drive/mask_rcnn_damage_detection/customImages/train/via_region_data.json"

**Comment by yhc1994** [comment]
Have you solved this problem, please share what you did

**Comment by may-phyu** [comment]
You can run like this
python custom.py train --dataset=(your dataset folder path) --weights=coco

**Comment by ayush1427** [comment]
I am getting the same error on training the balloon.py file in google colab. The command that I am using to train the balloon.py file is as follow:
!python balloon.py train --dataset=Mask_RCNN-master/dataset --weights=coco

Error that I am getting is as:

Traceback (most recent call last):
  File "balloon.py", line 364, in <module>
    train(model)
  File "balloon.py", line 183, in train
    dataset_train.load_balloon(args.dataset, "train")
  File "balloon.py", line 112, in load_balloon
    annotations1 = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
FileNotFoundError: [Errno 2] No such file or directory: 'Mask_RCNN-master/dataset/train/via_region_data.json' 

I am trying this from three days. If you have solved. Please help me.

**Comment by may-phyu** [comment]
> I am getting the same error on training the balloon.py file in google colab. The command that I am using to train the balloon.py file is as follow:
> !python balloon.py train --dataset=Mask_RCNN-master/dataset --weights=coco
> 
> Error that I am getting is as:
> 
> Traceback (most recent call last):
> File "balloon.py", line 364, in
> train(model)
> File "balloon.py", line 183, in train
> dataset_train.load_balloon(args.dataset, "train")
> File "balloon.py", line 112, in load_balloon
> annotations1 = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
> FileNotFoundError: [Errno 2] No such file or directory: 'Mask_RCNN-master/dataset/train/via_region_data.json'
> 
> I am trying this from three days. If you have solved. Please help me.

Hi, friend
Actually I am just a beginner so I can't explain very well so sorry for that. It really worked for me. Now I run again like this     
python custom.py train dataset=C;\Users\HP_PC01\Desktop\Mask_RCNN_damage_detection\customImages --weights=
coco
It still works so please try again with your dataset path. Hope to solve this stage

**Comment by priya-dwivedi** [comment]
Thanks @may-phyu. I agree with your suggestion. Please make sure that the --dataset argument has the correct path to your input. Another check you can add is print statements inside the code to double check the path it is reading in.
