### ISSUE TITLE
Can someone guide me on how to edit config file?

### ISSUE THREAD

**Issue by arsalan993** [priya-dwivedi/Deep-Learning#9]
Also can someone share the edited and non-edited version of config so that i can compare and able to understand ,where and why to edit.

**Comment by priya-dwivedi** [comment]
Hey Devang,

The easiest way to understand about config files is to go through the pets tutorial that the object detection team has shared. Please try to download the dataset and follow each step along with instructions. It really helps get a better understanding for how to replicate for your own dataset.'

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md
