### ISSUE TITLE
Residual_Networks_yourself.ipynb has problem

### ISSUE THREAD

**Issue by CharmingJohn** [priya-dwivedi/Deep-Learning#90]
[Residual_Networks_yourself.ipynb](https://github.com/priya-dwivedi/Deep-Learning/tree/master/resnet_keras)

when I run the model = ResNet50(*args)

> TypeError                                 Traceback (most recent call last)
> <ipython-input-5-383ade38d424> in <module>
> ----> 1 model = ResNet50(input_shape = (64, 64, 3), classes = 6)
> 
> <ipython-input-4-39fa060f05f2> in ResNet50(input_shape, classes)
>      25 
>      26     #Stage 2
> ---> 27     X = convolutional_block(X, f=3, filters = [64, 64, 256], stage = 2, block = 'a', s = 1)
>      28     X = identity_block(X, 3, [64, 64, 256], stage = 2, block = 'b')
>      29     X = identity_block(X, 3, [64, 64, 256], stage = 2, block = 'c')
> 
> <ipython-input-3-bf0a9a4a9e17> in convolutional_block(X, f, filters, stage, block, s)
>      34     #Third component of main path
>      35     X = Conv2D(filters = F3, kerenl_size = (1,1), strides = (1,1), padding = 'valid', name = conv_name_base + '2c',
> ---> 36                kernel_initializer = glorot_uniform(seed = 0))(X)
>      37     X = BatchNormalization(axis = 3, name = bn_name_base + '2c')(X)
>      38 
> 
> TypeError: __init__() missing 1 required positional argument: 'kernel_size'

Here is error log. would you please help me??

**Comment by priya-dwivedi** [comment]
Please specify kernel size =f as an input argument to your code. It is used in the line below:

 X = Conv2D(filters = F2, kernel_size = (f, f), strides = (1,1), padding = 'same', name = conv_name_base + '2b', kernel_initializer = glorot_uniform(seed=0))(X)
