### ISSUE TITLE
Resnet dataset

### ISSUE THREAD

**Issue by payal211** [priya-dwivedi/Deep-Learning#94]
Hi @priya-dwivedi 

I am working on resnet keras for custom data. How do I make train_signs.h5 and test_sign.h5 for my own dataset?

Can you please explain this?

If anyone knows the data format what is train_x_orig, train_y_orig, test_x_orig and test_y_orig ?
Any help would be appreciated.
Thank you.

**Comment by priya-dwivedi** [comment]
Typically train_x and test_x would be images. You can load them as numpy arrays. The train_y and test_y would be labels.

**Comment by payal211** [comment]
Yes. I got it. Thank you so much.

Sent from my Windows Phone
________________________________
